# Generated by Django 4.0.6 on 2022-07-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='integrante_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('daily_work_hours', models.FloatField()),
                ('pets', models.CharField(blank=True, max_length=20, null=True)),
                ('data_creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
