# Generated by Django 4.0.6 on 2022-07-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0003_alter_integrantes_data_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='data_creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
