# Generated by Django 4.0.6 on 2022-07-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrantes', '0004_alter_integrantes_data_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrantes',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
